[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
  
[window]
padding.x = 20
padding.y = 20
opacity = 0.95
decorations = "Buttonless"
dimensions.columns = 160
dimensions.lines   = 50
  
[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18

[general]
import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]
