-- Catppuccin: Macchiato (тёмная синяя палитра)
return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "macchiato", -- варианты: latte, frappe, macchiato, mocha
      transparent_background = false,
      term_colors = true,
      dim_inactive = {
        enabled = false,
      },
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
        operators = {},
      },
      custom_highlights = function(colors)
        return {
          -- Яркие цвета для синтаксических элементов
          ["@string"] = { fg = colors.yellow, style = {} },
          ["@string.special"] = { fg = colors.yellow, style = {} },
          ["@function"] = { fg = colors.blue, style = {} },
          ["@function.call"] = { fg = colors.blue, style = {} },
          ["@function.builtin"] = { fg = colors.sapphire, style = {} },
          ["@function.method"] = { fg = colors.blue, style = {} },
          ["@method"] = { fg = colors.blue, style = {} },
          ["@method.call"] = { fg = colors.blue, style = {} },
          ["@keyword"] = { fg = colors.mauve, style = {} },
          ["@keyword.function"] = { fg = colors.mauve, style = {} },
          ["@keyword.return"] = { fg = colors.mauve, style = {} },
          ["@keyword.operator"] = { fg = colors.mauve, style = {} },
          ["@keyword.conditional"] = { fg = colors.mauve, style = {} },
          ["@variable"] = { fg = colors.lavender, style = {} },
          ["@variable.builtin"] = { fg = colors.red, style = {} },
          ["@variable.parameter"] = { fg = colors.maroon, style = {} },
          ["@parameter"] = { fg = colors.maroon, style = {} },
          ["@number"] = { fg = colors.peach, style = {} },
          ["@boolean"] = { fg = colors.peach, style = {} },
          ["@operator"] = { fg = colors.sky, style = {} },
          ["@property"] = { fg = colors.flamingo, style = {} },
          ["@field"] = { fg = colors.flamingo, style = {} },
          ["@type"] = { fg = colors.sapphire, style = {} },
          ["@type.builtin"] = { fg = colors.blue, style = {} },
          ["@type.definition"] = { fg = colors.sapphire, style = {} },
          ["@constant"] = { fg = colors.peach, style = {} },
          ["@constant.builtin"] = { fg = colors.red, style = {} },
          ["@constant.macro"] = { fg = colors.mauve, style = {} },
          ["@namespace"] = { fg = colors.teal, style = {} },
          ["@module"] = { fg = colors.teal, style = {} },
          ["@label"] = { fg = colors.teal, style = {} },
          ["@punctuation.delimiter"] = { fg = colors.overlay2, style = {} },
          ["@punctuation.bracket"] = { fg = colors.overlay2, style = {} },
          ["@punctuation.special"] = { fg = colors.overlay2, style = {} },
          ["@comment"] = { fg = colors.surface2, style = { "italic" } },
          ["@text"] = { fg = colors.text, style = {} },
          ["@text.emphasis"] = { fg = colors.mauve, style = { "italic" } },
          ["@text.strong"] = { fg = colors.mauve, style = { "bold" } },
        }
      end,
      integrations = {
        cmp = true,
        gitsigns = true,
        nvimtree = true,
        treesitter = true,
        telescope = { enabled = true },
        notify = true,
        mini = true,
        which_key = true,
        noice = true,
        indent_blankline = { enabled = true },
        lsp_trouble = true,
      },
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin")
    end,
  },
}

